
export const LOGIN = 'LOGIN'
export const USER_IS_LOGGED = 'USER_IS_LOGGED'
export const SET_USER_INFO = 'SET_USET_INFO'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const LOGIN_AUTHENTICATION_FAILED = 'LOGIN_AUTHENTICATION_FAILED'
export const LOGIN_SAVE_RECOVERY_KEY = 'LOGIN_SAVE_RECOVERY_KEY'